# Generated by Django 5.2.6 on 2025-10-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classgroup_student_enrollment_classgroup_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='essay',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='assigned', max_length=50),
        ),
    ]
