# Generated by Django 5.2.6 on 2025-10-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_level_alter_essay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='core.student'),
            preserve_default=False,
        ),
    ]
