# Generated by Django 5.2.6 on 2025-10-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_essay_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='user',
        ),
    ]
