# Generated by Django 5.2.6 on 2025-10-19 06:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_essay_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentstudent',
            options={'verbose_name': 'Parent-Student Relationship', 'verbose_name_plural': 'Parent-Student Relationships'},
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(default='Basic Plan', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_parent',
            },
        ),
        migrations.AlterField(
            model_name='parentstudent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent'),
        ),
    ]
